---
name: Test

on:
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib
  SIMULATOR_DESTINATION: platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1

jobs:
  test:
    name: Test
    runs-on: macos-14-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Setup Ruby
        uses: ruby/setup-ruby@70da3bbf44ac06db1b0547ce2acc9380a5270d1e # v1.175.0
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: Cache Mint Packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM Packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install yeetd
        run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &

      - name: Setup
        run: |
          brew install mint xcbeautify
          ./Scripts/bootstrap.sh

      - name: Build and Test
        run: |
          set -o pipefail && \
            xcodebuild test \
            -project Authenticator.xcodeproj \
            -scheme Authenticator \
            -configuration Debug \
            -destination "${{ env.SIMULATOR_DESTINATION }}" \
            -resultBundlePath build/AuthenticatorTests.xcresult \
            -derivedDataPath build/DerivedData \
            | xcbeautify --renderer github-actions

      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
